/* Theme Lab: the ten design directions, as data.

   Each entry is one complete visual system for the same game. The
   factory (themes/lab/factory.js) turns an entry into an ordinary
   chassis theme module (the same contract as themes/standard.js), so
   the game engine never sees any of this: rules, moves, turns and the
   AI are the chassis's and the engine's, untouched.

   What each entry decides:
     colors      semantic tokens (become --bg-primary, --accent-primary ...)
     typography  faces, weights, tracking, case
     spacing, borders, shadows   the chrome's geometry
     board       how the playing surface is made and marked
     pieces      the pieces' material, outline and printed mark
     indicator   how a legal move is drawn; selection, landing
     hud         which composition the in-game read-out takes
     animation   pace and the transition language
     materials   a line on the physical make, for the lab's notes
     lighting    the light rig's colours and strengths, pitch, exposure
     audio       which voice of the audio manager speaks for it */

const FONT = (q) => `https://fonts.googleapis.com/css2?${q}&display=swap`;

export const LAB_SPECS = [
  {
    id: "swiss",
    num: "01",
    name: "Swiss Design",
    short: "SWISS",
    tagline: "The International Typographic Style: a rational grid, one red, nothing extra.",
    colors: {
      bgPrimary: "#F8F9FA", bgSecondary: "#ECEDEE", surface: "#FFFFFF",
      textPrimary: "#000000", textSecondary: "#5C5F63",
      accentPrimary: "#E63946", accentSecondary: "#000000",
      boardSurface: "#F4F4F2", boardGrid: "#111111",
      pieceDark: "#111111", pieceLight: "#FAFAF8", inkOnDark: "#FFFFFF", inkOnLight: "#000000",
    },
    typography: {
      url: FONT("family=Inter+Tight:wght@400;500;700;800;900"),
      display: "'Helvetica Neue', Helvetica, 'Inter Tight', Arial, sans-serif",
      body: "'Helvetica Neue', Helvetica, 'Inter Tight', Arial, sans-serif",
      mono: "'Helvetica Neue', Helvetica, 'Inter Tight', Arial, sans-serif",
      displayWeight: 800, tracking: "-0.035em", labelTracking: "0.02em", labelCase: "none",
    },
    spacing: { unit: 8, gutter: 24 },
    borders: { width: 1, radius: 0, color: "#000000" },
    shadows: { x: 0, y: 0, blur: 0, opacity: 0, color: "0,0,0" },
    board: {
      paint: "swissPrint", grid: "hairline", gridOpacity: 0.55, sideColor: 0xe9e9e6, roughness: 0.92,
      goal: "rule", coords: "margin",
    },
    pieces: {
      edgeRadius: 0.018, outline: { t: 0.008, dark: 0x111111, light: 0x111111 },
      dark: { color: 0x151515, roughness: 0.9, metalness: 0 },
      light: { color: 0xf2f2ef, roughness: 0.92, metalness: 0 },
      mark: null,
    },
    indicator: "corners", selection: "redFrame", landing: "tick",
    ground: "sheet",
    hud: "swiss",
    animation: { speed: 160, ease: "cubic-bezier(.2,0,0,1)", enter: "wipe" },
    materials: "Matte polymer board, printed paper finish; flat matte tokens.",
    lighting: {
      toneMapping: "none", exposure: 1, pitch: 0.62,
      ambient: { color: 0xffffff, intensity: 0.42 }, hemi: { sky: 0xffffff, ground: 0xdedede, intensity: 0.34 },
      key: { color: 0xffffff, intensity: 0.62 }, fill: { color: 0xffffff, intensity: 0.2 }, back: { color: 0xffffff, intensity: 0.1 },
    },
    audio: "swiss",
  },
  {
    id: "bauhaus",
    num: "02",
    name: "Bauhaus",
    short: "BAUHAUS",
    tagline: "Circle, square, triangle. Form follows function, in primary paint.",
    colors: {
      bgPrimary: "#E9E3D5", bgSecondary: "#D8D0BD", surface: "#F3EEE2",
      textPrimary: "#1F1D1B", textSecondary: "#5B564E",
      accentPrimary: "#D1362A", accentSecondary: "#1F4EA3", accentTertiary: "#E8B321",
      boardSurface: "#D9D3C4", boardGrid: "#3A3834",
      pieceDark: "#C8332A", pieceLight: "#1F4EA3", inkOnDark: "#F3EEE2", inkOnLight: "#F3EEE2",
    },
    typography: {
      url: FONT("family=Jost:wght@400;500;600;700;800"),
      display: "'Jost', 'Futura', 'Century Gothic', sans-serif",
      body: "'Jost', 'Futura', 'Century Gothic', sans-serif",
      mono: "'Jost', 'Futura', sans-serif",
      displayWeight: 700, tracking: "0.01em", labelTracking: "0.16em", labelCase: "lowercase",
    },
    spacing: { unit: 8, gutter: 22 },
    borders: { width: 2, radius: 0, color: "#1F1D1B" },
    shadows: { x: 0, y: 6, blur: 16, opacity: 0.18, color: "31,29,27" },
    board: {
      paint: "bauhausPaper", grid: "ink", gridOpacity: 0.7, sideColor: 0x2e2c29, roughness: 0.95,
      goal: "band", coords: null,
    },
    pieces: {
      edgeRadius: 0.04, outline: null,
      dark: { color: 0xc8332a, roughness: 0.55, metalness: 0, clearcoat: 0.25 },
      light: { color: 0x1f4ea3, roughness: 0.55, metalness: 0, clearcoat: 0.25 },
      mark: "shape",
    },
    indicator: "triangle", selection: "yellowDisc", landing: "ring",
    ground: "bauhausForms",
    hud: "bauhaus",
    animation: { speed: 240, ease: "cubic-bezier(.34,1.3,.64,1)", enter: "stack" },
    materials: "Cold-pressed paper board; manufactured painted plastic pieces.",
    lighting: {
      toneMapping: "aces", exposure: 1.05, pitch: 0.78,
      ambient: { color: 0xfff6e8, intensity: 0.24 }, hemi: { sky: 0xfffaf0, ground: 0x8a7c66, intensity: 0.34 },
      key: { color: 0xfff1dc, intensity: 1.15 }, fill: { color: 0xe8efff, intensity: 0.32 }, back: { color: 0xffffff, intensity: 0.2 },
    },
    audio: "bauhaus",
  },
  {
    id: "destijl",
    num: "03",
    name: "De Stijl",
    short: "DE STIJL",
    tagline: "Mondrian's order: black structure raised, white fields recessed, primaries where they mean something.",
    colors: {
      bgPrimary: "#F4F2EC", bgSecondary: "#FFFFFF", surface: "#FFFFFF",
      textPrimary: "#0E0E0E", textSecondary: "#4A4A4A",
      accentPrimary: "#D7261E", accentSecondary: "#1B3FA0", accentTertiary: "#F2C914",
      boardSurface: "#F6F5F0", boardGrid: "#0E0E0E",
      pieceDark: "#D7261E", pieceLight: "#1B3FA0", inkOnDark: "#FFFFFF", inkOnLight: "#FFFFFF",
    },
    typography: {
      url: FONT("family=Rubik+Mono+One&family=Karla:wght@400;600;800"),
      display: "'Rubik Mono One', 'Arial Black', sans-serif",
      body: "'Karla', 'Helvetica Neue', Arial, sans-serif",
      mono: "'Karla', Arial, sans-serif",
      displayWeight: 400, tracking: "0.02em", labelTracking: "0.12em", labelCase: "uppercase",
    },
    spacing: { unit: 8, gutter: 20 },
    borders: { width: 6, radius: 0, color: "#0E0E0E" },
    shadows: { x: 0, y: 0, blur: 0, opacity: 0, color: "0,0,0" },
    board: {
      paint: "destijlField", grid: "bars", gridOpacity: 1, sideColor: 0x0e0e0e, roughness: 0.4, clearcoat: 0.6,
      goal: "primaries", coords: null,
    },
    pieces: {
      edgeRadius: 0.012, outline: { t: 0.012, dark: 0x0e0e0e, light: 0x0e0e0e },
      dark: { color: 0xd7261e, roughness: 0.18, metalness: 0, clearcoat: 1 },
      light: { color: 0x1b3fa0, roughness: 0.18, metalness: 0, clearcoat: 1 },
      mark: "cabezaYellow",
    },
    indicator: "recess", selection: "yellowField", landing: "depress",
    ground: "mondrian",
    hud: "destijl",
    animation: { speed: 200, ease: "steps(4, end)", enter: "bars" },
    materials: "Enamel fields, porcelain-glazed blocks, structural black bars.",
    lighting: {
      toneMapping: "none", exposure: 1, pitch: 0.7,
      ambient: { color: 0xffffff, intensity: 0.36 }, hemi: { sky: 0xffffff, ground: 0xcccccc, intensity: 0.34 },
      key: { color: 0xffffff, intensity: 0.78 }, fill: { color: 0xffffff, intensity: 0.24 }, back: { color: 0xffffff, intensity: 0.2 },
    },
    audio: "destijl",
  },
  {
    id: "elementarism",
    num: "04",
    name: "Elementarism",
    short: "ELEMENTARISM",
    tagline: "Van Doesburg's diagonal: the grid set against a 45° counter-composition, every move a vector.",
    colors: {
      bgPrimary: "#1C2127", bgSecondary: "#262C33", surface: "#2E353D",
      textPrimary: "#EEF1F4", textSecondary: "#9AA5B1",
      accentPrimary: "#FF5A1F", accentSecondary: "#C9D2DB",
      boardSurface: "#B9C0C7", boardGrid: "#2A3038",
      pieceDark: "#2A3038", pieceLight: "#D5DBE1", inkOnDark: "#FF5A1F", inkOnLight: "#1C2127",
    },
    typography: {
      url: FONT("family=Saira+Condensed:wght@500;700;800&family=Saira:wght@400;500;600"),
      display: "'Saira Condensed', 'Arial Narrow', sans-serif",
      body: "'Saira', 'Helvetica Neue', Arial, sans-serif",
      mono: "'Saira Condensed', 'Arial Narrow', sans-serif",
      displayWeight: 800, tracking: "0.02em", labelTracking: "0.22em", labelCase: "uppercase",
    },
    spacing: { unit: 8, gutter: 22 },
    borders: { width: 1, radius: 0, color: "#C9D2DB" },
    shadows: { x: 0, y: 8, blur: 22, opacity: 0.35, color: "0,0,0" },
    board: {
      paint: "brushedDiagonal", grid: "machined", gridOpacity: 0.8, sideColor: 0x6d7680, roughness: 0.38, metalness: 0.75,
      goal: "hatch", coords: null,
    },
    pieces: {
      edgeRadius: 0.02, outline: null,
      dark: { color: 0x3a424c, roughness: 0.34, metalness: 0.85 },
      light: { color: 0xc9d0d8, roughness: 0.28, metalness: 0.9 },
      mark: "diamond",
    },
    indicator: "vector", selection: "diagonalFrame", landing: "streak",
    ground: "diagonalPlanes",
    hud: "elementarism",
    animation: { speed: 220, ease: "cubic-bezier(.7,0,.2,1)", enter: "slice" },
    materials: "Brushed aluminium board, machined grooves; anodised metal pieces.",
    lighting: {
      toneMapping: "aces", exposure: 1.2, pitch: 0.9,
      ambient: { color: 0xdfe8f2, intensity: 0.2 }, hemi: { sky: 0xe6eef8, ground: 0x2a3038, intensity: 0.5 },
      key: { color: 0xffffff, intensity: 1.35 }, fill: { color: 0xffc9a8, intensity: 0.4 }, back: { color: 0xb8d4ff, intensity: 0.55 },
    },
    audio: "elementarism",
  },
  {
    id: "brutalist",
    num: "05",
    name: "Brutalism",
    short: "BRUTALISM",
    tagline: "Béton brut. Poured, cast, stencilled. Mass over ornament.",
    colors: {
      bgPrimary: "#B8B4AC", bgSecondary: "#9E9A92", surface: "#CFCBC3",
      textPrimary: "#111111", textSecondary: "#3B3936",
      accentPrimary: "#111111", accentSecondary: "#FF3B00",
      boardSurface: "#A9A59D", boardGrid: "#2A2826",
      pieceDark: "#2B2A28", pieceLight: "#C9C5BC", inkOnDark: "#D8D4CB", inkOnLight: "#161514",
    },
    typography: {
      url: FONT("family=JetBrains+Mono:wght@400;700;800"),
      display: "'JetBrains Mono', 'Courier New', monospace",
      body: "'JetBrains Mono', 'Courier New', monospace",
      mono: "'JetBrains Mono', 'Courier New', monospace",
      displayWeight: 800, tracking: "-0.02em", labelTracking: "0.04em", labelCase: "uppercase",
    },
    spacing: { unit: 8, gutter: 16 },
    borders: { width: 4, radius: 0, color: "#111111" },
    shadows: { x: 8, y: 8, blur: 0, opacity: 1, color: "17,17,17" },
    board: {
      paint: "concrete", grid: "groove", gridOpacity: 0.9, sideColor: 0x8f8b84, roughness: 1,
      goal: "stencil", coords: "stencil",
    },
    pieces: {
      edgeRadius: 0.008, outline: null,
      dark: { color: 0x2f2d2a, roughness: 0.62, metalness: 0.7, texture: "iron" },
      light: { color: 0xbdb9b0, roughness: 1, metalness: 0, texture: "concrete" },
      mark: "code",
    },
    indicator: "block", selection: "hardFrame", landing: "dust",
    ground: "plinth",
    hud: "brutalist",
    animation: { speed: 90, ease: "linear", enter: "slam" },
    materials: "Raw board-formed concrete; cast iron and concrete monoliths.",
    lighting: {
      toneMapping: "aces", exposure: 1.1, pitch: 0.84,
      ambient: { color: 0xf0f0f0, intensity: 0.12 }, hemi: { sky: 0xe8ecf0, ground: 0x55524d, intensity: 0.36 },
      key: { color: 0xffffff, intensity: 1.55 }, fill: { color: 0xdde4ec, intensity: 0.12 }, back: { color: 0xffffff, intensity: 0.1 },
    },
    audio: "brutalist",
  },
  {
    id: "newTypography",
    num: "06",
    name: "New Typography",
    short: "NEW TYPOGRAPHY",
    tagline: "After Tschichold: the page is the architecture, the board a figure set into it.",
    colors: {
      bgPrimary: "#F1EADB", bgSecondary: "#E6DDC9", surface: "#F7F1E4",
      textPrimary: "#141210", textSecondary: "#5E5850",
      accentPrimary: "#D0021B", accentSecondary: "#141210",
      boardSurface: "#F3ECDD", boardGrid: "#141210",
      pieceDark: "#141210", pieceLight: "#F1EADB", inkOnDark: "#F1EADB", inkOnLight: "#141210",
    },
    typography: {
      url: FONT("family=Archivo:wdth,wght@62..125,400;62..125,600;62..125,800;62..125,900"),
      display: "'Archivo', 'Akzidenz-Grotesk', 'Helvetica Neue', Arial, sans-serif",
      body: "'Archivo', 'Helvetica Neue', Arial, sans-serif",
      mono: "'Archivo', Arial, sans-serif",
      displayWeight: 900, tracking: "-0.04em", labelTracking: "0.14em", labelCase: "uppercase",
    },
    spacing: { unit: 6, gutter: 26 },
    borders: { width: 3, radius: 0, color: "#141210" },
    shadows: { x: 0, y: 0, blur: 0, opacity: 0, color: "0,0,0" },
    board: {
      paint: "parchment", grid: "ink", gridOpacity: 0.8, sideColor: 0x141210, roughness: 0.95,
      goal: "redRule", coords: "margin",
    },
    pieces: {
      edgeRadius: 0.02, outline: null,
      dark: { color: 0x181614, roughness: 0.85, metalness: 0 },
      light: { color: 0xefe7d6, roughness: 0.9, metalness: 0 },
      mark: "glyph",
    },
    indicator: "glyph", selection: "redUnderline", landing: "inkBlot",
    ground: "typeSheet",
    hud: "newTypography",
    animation: { speed: 180, ease: "cubic-bezier(.25,.1,.25,1)", enter: "set" },
    materials: "Parchment board, letterpress ink; printed type blocks.",
    lighting: {
      toneMapping: "none", exposure: 1, pitch: 0.58,
      ambient: { color: 0xfffaf0, intensity: 0.4 }, hemi: { sky: 0xfffcf4, ground: 0xc8bca4, intensity: 0.34 },
      key: { color: 0xfff8ea, intensity: 0.6 }, fill: { color: 0xffffff, intensity: 0.18 }, back: { color: 0xffffff, intensity: 0.1 },
    },
    audio: "newTypography",
  },
  {
    id: "corporateSwiss",
    num: "07",
    name: "Corporate Swiss",
    short: "CORPORATE SWISS",
    tagline: "A 1960s information system: departure board, annual report, engineering console.",
    colors: {
      bgPrimary: "#0F1D33", bgSecondary: "#16284A", surface: "#1B2F52",
      textPrimary: "#F2F4F7", textSecondary: "#8C9AB3",
      accentPrimary: "#FFC400", accentSecondary: "#5E6E88",
      boardSurface: "#22385E", boardGrid: "#8FA3C4",
      pieceDark: "#1A2B4A", pieceLight: "#D8DEE8", inkOnDark: "#FFC400", inkOnLight: "#0F1D33",
    },
    typography: {
      url: FONT("family=Barlow+Semi+Condensed:wght@400;500;600;700&family=Share+Tech+Mono"),
      display: "'Barlow Semi Condensed', 'Helvetica Neue', Arial, sans-serif",
      body: "'Barlow Semi Condensed', 'Helvetica Neue', Arial, sans-serif",
      mono: "'Share Tech Mono', 'Courier New', monospace",
      displayWeight: 700, tracking: "0.01em", labelTracking: "0.18em", labelCase: "uppercase",
    },
    spacing: { unit: 4, gutter: 16 },
    borders: { width: 1, radius: 2, color: "#5E6E88" },
    shadows: { x: 0, y: 2, blur: 6, opacity: 0.45, color: "0,0,0" },
    board: {
      paint: "anodized", grid: "engraved", gridOpacity: 0.75, sideColor: 0x0c182b, roughness: 0.32, metalness: 0.7,
      goal: "safety", coords: "engraved",
    },
    pieces: {
      edgeRadius: 0.024, outline: null,
      dark: { color: 0x1d3050, roughness: 0.3, metalness: 0.8 },
      light: { color: 0xcfd6e2, roughness: 0.26, metalness: 0.85 },
      mark: "serial",
    },
    indicator: "brackets", selection: "yellowBrackets", landing: "scan",
    ground: "console",
    hud: "corporateSwiss",
    animation: { speed: 140, ease: "cubic-bezier(.4,0,.2,1)", enter: "flap" },
    materials: "Anodised aluminium, micro-engraved markings; machined components.",
    lighting: {
      toneMapping: "aces", exposure: 1.25, pitch: 0.74,
      ambient: { color: 0xe6eeff, intensity: 0.22 }, hemi: { sky: 0xdfe8ff, ground: 0x0f1d33, intensity: 0.46 },
      key: { color: 0xffffff, intensity: 1.2 }, fill: { color: 0xcfe0ff, intensity: 0.34 }, back: { color: 0xfff1c8, intensity: 0.4 },
    },
    audio: "corporateSwiss",
  },
  {
    id: "neoBrutalist",
    num: "08",
    name: "Neo-Brutalism",
    short: "NEO-BRUTALISM",
    tagline: "Flat paint, thick outlines, hard offset shadows, and a lot of nerve.",
    colors: {
      bgPrimary: "#C9F2DD", bgSecondary: "#FFF4D6", surface: "#FFFFFF",
      textPrimary: "#000000", textSecondary: "#2B2B2B",
      accentPrimary: "#FF4F9A", accentSecondary: "#7B5CFF", accentTertiary: "#FFE14D",
      boardSurface: "#D8CCFF", boardGrid: "#000000",
      pieceDark: "#FF4F9A", pieceLight: "#FFE14D", inkOnDark: "#000000", inkOnLight: "#000000",
    },
    typography: {
      url: FONT("family=Dela+Gothic+One&family=Lexend:wght@400;600;800"),
      display: "'Dela Gothic One', 'Arial Black', sans-serif",
      body: "'Lexend', 'Helvetica Neue', Arial, sans-serif",
      mono: "'Lexend', Arial, sans-serif",
      displayWeight: 400, tracking: "0em", labelTracking: "0.04em", labelCase: "uppercase",
    },
    spacing: { unit: 8, gutter: 18 },
    borders: { width: 3, radius: 10, color: "#000000" },
    shadows: { x: 5, y: 5, blur: 0, opacity: 1, color: "0,0,0" },
    board: {
      paint: "flatPaint", grid: "thick", gridOpacity: 1, sideColor: 0x000000, roughness: 0.6,
      goal: "mint", coords: null,
    },
    pieces: {
      edgeRadius: 0.07, outline: { t: 0.03, dark: 0x000000, light: 0x000000 },
      dark: { color: 0xff4f9a, roughness: 0.22, metalness: 0, clearcoat: 1 },
      light: { color: 0xffe14d, roughness: 0.22, metalness: 0, clearcoat: 1 },
      mark: "sticker", hardShadow: true,
    },
    indicator: "pop", selection: "popFrame", landing: "pop",
    ground: "offsetSlab",
    hud: "neoBrutalist",
    animation: { speed: 120, ease: "cubic-bezier(.3,1.6,.5,1)", enter: "pop" },
    materials: "Flat painted board; glossy injection-moulded plastic tokens.",
    lighting: {
      toneMapping: "none", exposure: 1, pitch: 0.72,
      ambient: { color: 0xffffff, intensity: 0.5 }, hemi: { sky: 0xffffff, ground: 0xd8ccff, intensity: 0.3 },
      key: { color: 0xffffff, intensity: 0.55 }, fill: { color: 0xffffff, intensity: 0.22 }, back: { color: 0xffffff, intensity: 0.15 },
    },
    audio: "neoBrutalist",
  },
  {
    id: "minimalMono",
    num: "09",
    name: "Minimal Mono",
    short: "MINIMAL MONO",
    tagline: "Reduction to the edge of disappearance. Black, white, and the grey of opacity.",
    colors: {
      bgPrimary: "#FFFFFF", bgSecondary: "#FFFFFF", surface: "#FFFFFF",
      textPrimary: "#000000", textSecondary: "rgba(0,0,0,0.45)",
      accentPrimary: "#000000", accentSecondary: "rgba(0,0,0,0.3)",
      boardSurface: "#FFFFFF", boardGrid: "#000000",
      pieceDark: "#0A0A0A", pieceLight: "#FFFFFF", inkOnDark: "#FFFFFF", inkOnLight: "#000000",
    },
    typography: {
      url: FONT("family=DM+Mono:wght@300;400&family=DM+Sans:opsz,wght@9..40,300;9..40,400"),
      display: "'DM Sans', 'Helvetica Neue', Arial, sans-serif",
      body: "'DM Sans', 'Helvetica Neue', Arial, sans-serif",
      mono: "'DM Mono', 'Courier New', monospace",
      displayWeight: 300, tracking: "0.01em", labelTracking: "0.2em", labelCase: "lowercase",
    },
    spacing: { unit: 8, gutter: 28 },
    borders: { width: 1, radius: 0, color: "rgba(0,0,0,0.14)" },
    shadows: { x: 0, y: 0, blur: 0, opacity: 0, color: "0,0,0" },
    board: {
      paint: "pureWhite", grid: "crosshair", gridOpacity: 0.35, sideColor: 0xffffff, roughness: 1,
      goal: "ticks", coords: null,
    },
    pieces: {
      edgeRadius: 0.03, outline: { t: 0.006, dark: 0x0a0a0a, light: 0x0a0a0a },
      dark: { color: 0x0a0a0a, roughness: 1, metalness: 0 },
      light: { color: 0xffffff, roughness: 1, metalness: 0 },
      mark: null,
    },
    indicator: "crosshair", selection: "quietCorners", landing: null,
    ground: "void",
    hud: "minimalMono",
    animation: { speed: 260, ease: "cubic-bezier(.4,0,.2,1)", enter: "fade" },
    materials: "Pure matte white; pure matte black. Nothing else.",
    lighting: {
      toneMapping: "none", exposure: 1, pitch: 0.5,
      ambient: { color: 0xffffff, intensity: 0.56 }, hemi: { sky: 0xffffff, ground: 0xffffff, intensity: 0.3 },
      key: { color: 0xffffff, intensity: 0.42 }, fill: { color: 0xffffff, intensity: 0.12 }, back: { color: 0xffffff, intensity: 0.06 },
    },
    audio: "minimalMono",
  },
  {
    id: "ultimateFusion",
    num: "10",
    name: "Ultimate Fusion",
    short: "ULTIMATE FUSION",
    tagline: "Swiss measure, De Stijl structure, Brutalist mass: one architectural machine.",
    colors: {
      bgPrimary: "#2B2B2B", bgSecondary: "#1F1F1F", surface: "#EAE6DF",
      textPrimary: "#EAE6DF", textSecondary: "#A39E95", panelInk: "#2B2B2B",
      accentPrimary: "#C1121F", accentSecondary: "#F2B705", accentTertiary: "#FDF0D5",
      boardSurface: "#E3DED5", boardGrid: "#2B2B2B",
      pieceDark: "#2B2B2B", pieceLight: "#EAE6DF", inkOnDark: "#F2B705", inkOnLight: "#2B2B2B",
    },
    typography: {
      url: FONT("family=Schibsted+Grotesk:wght@500;700;900&family=Martian+Mono:wght@400;600"),
      display: "'Helvetica Neue', Helvetica, 'Schibsted Grotesk', Arial, sans-serif",
      body: "'Helvetica Neue', Helvetica, 'Schibsted Grotesk', Arial, sans-serif",
      mono: "'Martian Mono', 'Courier New', monospace",
      displayWeight: 900, tracking: "-0.03em", labelTracking: "0.1em", labelCase: "uppercase",
    },
    spacing: { unit: 8, gutter: 20 },
    borders: { width: 3, radius: 0, color: "#EAE6DF" },
    shadows: { x: 6, y: 6, blur: 0, opacity: 1, color: "10,10,10" },
    board: {
      paint: "composite", grid: "channels", gridOpacity: 1, sideColor: 0x3a3836, roughness: 0.85, metalness: 0.08,
      goal: "fusion", coords: "stencil",
    },
    pieces: {
      edgeRadius: 0.015, outline: null,
      dark: { color: 0x2d2c2a, roughness: 0.55, metalness: 0.55, texture: "paintedMetal" },
      light: { color: 0xe2ddd3, roughness: 0.9, metalness: 0.02, texture: "composite" },
      mark: "idCoord",
    },
    indicator: "slide", selection: "machineFrame", landing: "clamp",
    ground: "machine",
    hud: "ultimateFusion",
    animation: { speed: 200, ease: "cubic-bezier(.65,0,.35,1)", enter: "machine" },
    materials: "Weathered industrial composite, painted metal, raw stone channels.",
    lighting: {
      toneMapping: "aces", exposure: 1.18, pitch: 0.8,
      ambient: { color: 0xfff4e6, intensity: 0.16 }, hemi: { sky: 0xfaf2e6, ground: 0x3a3836, intensity: 0.4 },
      key: { color: 0xfff3e0, intensity: 1.4 }, fill: { color: 0xdfe6f0, intensity: 0.22 }, back: { color: 0xffe0b0, intensity: 0.3 },
    },
    audio: "ultimateFusion",
  },
];

export const LAB_IDS = LAB_SPECS.map((s) => s.id);
export const specById = (id) => LAB_SPECS.find((s) => s.id === id) || LAB_SPECS[0];
